version: "3"

services:
  :employee-consumer:
    build:
      context: ../employee-consumer
      dockerfile: ./Dockerfile
    ports:
    - 8081:8081

  employee-producer:
    build:
      context: ../employee-producer
      dockerfile: ./Dockerfile
    ports:
    - 8082:8082
    environment:
    - EMPLOYEE_CONSUMER_BASE_PATH=http://localhost:8081/employee-consumer
    depends_on:
    - employee-consumer
